// eslint-disable-next-line import/no-anonymous-default-export
export default [
    { id: 'Jeagerists', name: 'resources.categories.data.Jeagerists' },
    { id: 'Male', name: 'resources.categories.data.Male' },
    { id: 'Jeager Family', name: 'resources.categories.data.Jeager_Family' },
    { id: 'Wall Maria', name: 'resources.categories.data.Wall_Maria' },
    { id: 'Wall Rose', name: 'resources.categories.data.Wall_Rose' },
    { id: 'Wall Sheena', name: 'resources.categories.data.Wall_Sheena' },
    { id: 'Special Operations Squad', name: 'resources.categories.data.Special_Operations_Squad' },
    { id: 'Elite Squad', name: 'resources.categories.data.Elite_Squad' },
    { id: 'Characters', name: 'resources.categories.data.Characters' },
    { id: 'cadet Corps', name: 'resources.categories.data.cadet_Corps' },
    { id: 'Military', name: 'resources.categories.data.Military' },
    { id: 'Scout Regiment', name: 'resources.categories.data.Scout_Regiment' },
    { id: 'food', name: 'resources.categories.data.food' },
    { id: 'Intelligent Titans', name: 'resources.categories.data.Intelligent_Titans' },
    { id: 'Civilians', name: 'resources.categories.data.Civilians' },
    { id: 'Female', name: 'resources.categories.data.Female' },
    { id: 'Warrior Unit', name: 'resources.categories.data.Warrior_Unit'},
    { id: 'Liberio', name: 'resources.categories.data.Liberio' },
    { id: 'Ackerman clan', name: 'resources.categories.data.Ackerman_clan' },
    { id: 'Eldians', name: 'resources.categories.data.Eldians' },
    { id: 'Paradis', name: 'resources.categories.data.Paradis' },
    { id: 'Humans', name: 'resources.categories.data.Humans' },
    { id: 'Animals', name: 'resources.categories.data.Animals'}
];